# Generated by Django 5.1.3 on 2024-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialStatements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financials_upload",
                    models.FileField(upload_to="documents/financials/"),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Statements",
            },
        ),
    ]
